### ISSUE TITLE
set value instead of display after submit

### ISSUE THREAD

**Issue by zahrardn** [bostrowski/Pretius-APEX-Enhanced-Lov-Item#12]
Hi
when I submit the page, then value placed inside text item instead of display
and has js error like this "Uncaught not all variables bound"

**Comment by bostrowski** [comment]
@zahrardn 
As error states you should inspect your SQL query and session state. In your SQL query you are referencing variable that is not available when page loads.

If you want you can reproduce the issue at apex.oracle.com and share developer credentials.

**Comment by bostrowski** [comment]
@zahrardn 
the behavior you have described is a bug, workaround for it is described in #14. The official fix will be available soon with release `v1.0.5`.
