### ISSUE TITLE
IG Error with empty item

### ISSUE THREAD

**Issue by michele-pauluzzi** [bostrowski/Pretius-APEX-Enhanced-Lov-Item#26]
![immagine](https://user-images.githubusercontent.com/54415530/69830887-2f9c0500-1227-11ea-966d-5a83536e2a09.png)

![immagine](https://user-images.githubusercontent.com/54415530/69830906-45112f00-1227-11ea-98a9-27ff836c553a.png)

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/54415530/69831167-763e2f00-1228-11ea-86c5-7c278df96b65.gif)

If you have a row with a required item, empty it, go to another row , go back to it you get
TypeError: pValue is null

**Comment by bostrowski** [comment]
@michele-pauluzzi 
I assume it is after you downloaded not released v1.1.0? ;-) just asking.

**Comment by michele-pauluzzi** [comment]
Yes

**Comment by michele-pauluzzi** [comment]
fixed
