### ISSUE TITLE
Infinite loop when select row from report pop-up -  Oracle APEX 19.2 ISSUE‏‏

### ISSUE THREAD

**Issue by 4rass** [bostrowski/Pretius-APEX-Enhanced-Lov-Item#31]
# Im using oracle APEX 19.2, 
**When i select row/fake-chaeckbox the JS code get into infinite loop and all browser freeze:**

![image](https://user-images.githubusercontent.com/31360096/70264305-dab93b00-17a0-11ea-86bf-3c0aedd95424.png)

**But i can select my values from the autocomplete page item, and it selected the selected values:**
![image (2)](https://user-images.githubusercontent.com/31360096/70264482-2c61c580-17a1-11ea-9186-4a6983d4f993.png)

**If i click on some row it freeze, and the JS has a loop:**

![image (1)](https://user-images.githubusercontent.com/31360096/70264554-4ef3de80-17a1-11ea-93b7-b6ed65cd78c4.png)

### I copy the whole application to APEX 19.1 and it work like charm.
**Any ideas ?**

**Thanks.**

**Comment by 4rass** [comment]
![image](https://user-images.githubusercontent.com/31360096/70268364-fcb6bb80-17a8-11ea-9e36-317accd44b67.png)

**Comment by bostrowski** [comment]
@4rass 
If you are having the issue on Oracle APEX 19.2 then please recreate the issue at apex.oracle.com and send me developer credentials to ostrowski.bartosz@gmail.com so I can inspect the issue directly in your example application.

**Comment by 4rass** [comment]
My issue was on APEX **19.2** when i select the default selection:
![image](https://user-images.githubusercontent.com/31360096/70338796-3d204300-1856-11ea-83b5-6d250b80c73c.png)

On **19.1** it work like charm, so i just needed to unchecked the selection.
Thanks.

**Comment by bostrowski** [comment]
@4rass 
That is why I want you to reproduce the issue at apex.oracle.com so I can give it a closer look :-)
