### ISSUE TITLE
Set value lov

### ISSUE THREAD

**Issue by michele-pauluzzi** [bostrowski/Pretius-APEX-Enhanced-Lov-Item#34]
Simple case, button with a dynamic action set value to lov.
Error
![immagine](https://user-images.githubusercontent.com/54415530/70560618-36ad0680-1b89-11ea-94e0-4c22a9722833.png)

Workspace: mpgpi
User: demo
password: demodemo

page: lov

**Comment by bostrowski** [comment]
@michele-pauluzzi 
its the minor bug. The case is that **List of Values > Display Null Value > Null Return Value** is not set. 

Please download branch v1.1.1 which fix the issue and let me know about your test result.

**Comment by michele-pauluzzi** [comment]
This i fixed
